"""Dictionnaires métier utilisés par le parseur.

Ces listes sont volontairement éditables : quand le rapport de diagnostic signale
une race, une prestation ou un prénom non reconnu, il suffit de l'ajouter ici.
"""

MOIS = {
    "janvier": 1,
    "fevrier": 2,
    "mars": 3,
    "avril": 4,
    "mai": 5,
    "juin": 6,
    "juillet": 7,
    "aout": 8,
    "septembre": 9,
    "octobre": 10,
    "novembre": 11,
    "decembre": 12,
}

JOURS = {
    "lundi": 0,
    "mardi": 1,
    "mercredi": 2,
    "jeudi": 3,
    "vendredi": 4,
    "samedi": 5,
    "dimanche": 6,
}

# Fichiers dont le nom ne porte pas l'année. Le mois est dans le nom, l'année est
# déduite du seul emplacement libre dans la série continue décembre 2022 -> septembre 2026.
ANNEE_PAR_DEFAUT = {
    "clients juillet": 2023,
    "clients novembre": 2023,
}

# Espèces génériques : elles ne comptent pas comme une race quand une race
# précise est présente dans la même description.
GENERIQUES = {"chien", "chienne", "chiot", "chat", "chatte", "chaton"}

# Races : les variantes les plus longues doivent être testées en premier, le
# parseur trie donc cette liste par nombre de mots décroissant.
RACES = [
    "cavalier king charles",
    "chien chinois a crete",
    "chien de chasse",
    "chien de berger",
    "coton de tulear",
    "berger blanc suisse",
    "berger australien",
    "berger allemand",
    "berger de beauce",
    "berger belge",
    "berger des pyrenees",
    "bouledogue francais",
    "bouledogue anglais",
    "bouvier bernois",
    "husky de siberie",
    "chat croise angora",
    "sacre de birmanie",
    "west highland terrier",
    "terrier tibetain",
    "epagneul tibetain",
    "epagneul breton",
    "epagneul papillon",
    "epagneul nain",
    "cocker anglais",
    "cocker americain",
    "cocker spaniel",
    "cocker spanell",
    "dogue allemand",
    "dogue de bordeaux",
    "cane corso",
    "montagne des pyrenees",
    "berger des pyrenees",
    "berger picard",
    "shar pei",
    "sharpei",
    "bobtail",
    "golden retriever",
    "labrador retriever",
    "jack russell",
    "fox terrier",
    "bichon maltais",
    "bichon frise",
    "bichon havanais",
    "lhassa apso",
    "shih tzu",
    "shitzu",
    "chow chow",
    "chow-chow",
    "border collie",
    "bearded collie",
    "levrier afghan",
    "yorkshire terrier",
    "caniche nain",
    "caniche royal",
    "caniche toy",
    "spitz nain",
    "spitz loup",
    "spitz japonais",
    "maine coon",
    "norvegien",
    "chartreux",
    "ragdoll",
    "british shorthair",
    "british",
    "bengal",
    "sphynx",
    "siamois",
    "persan",
    "angora",
    "siberien",
    "yorkshire",
    "shiba inu",
    "shiba",
    "akita inu",
    "akita",
    "samoyede",
    "eurasier",
    "malinois",
    "beauceron",
    "briard",
    "schnauzer",
    "staffordshire",
    "staffy",
    "amstaff",
    "pitbull",
    "rottweiler",
    "doberman",
    "boxer",
    "beagle",
    "basset",
    "teckel",
    "chihuahua",
    "carlin",
    "pekinois",
    "papillon",
    "westie",
    "cairn",
    "scottish terrier",
    "airedale",
    "griffon",
    "setter",
    "braque",
    "pointer",
    "dalmatien",
    "dogue",
    "leonberg",
    "terre neuve",
    "saint bernard",
    "montagne des pyrenees",
    "colley",
    "shetland",
    "welsh corgi",
    "corgi",
    "bouvier",
    "labradoodle",
    "goldendoodle",
    "cockapoo",
    "loulou de pomeranie",
    "chien loup",
    "bouledogue",
    "dalmatien",
    "labrador",
    "caniche",
    "cocker",
    "bichon",
    "spitz",
    "pomeranian",
    "levrier",
    "barbet",
    "sheltie",
    "husky",
    "hovawart",
    "laika de lakoutie",
    "laika",
    "europeen",
    "lapin",
    "furet",
    "fox",
    "berger",
    "collie",
    "retriever",
    "terrier",
    "epagneul",
    "chienne",
    "chiot",
    "chaton",
    "chatte",
    "chat",
    "chien",
]

# Libellés d'affichage : les règles travaillent sans accents, l'affichage les remet.
LIBELLES = {
    "cavalier king charles": "Cavalier King Charles",
    "chien chinois a crete": "Chien chinois à crête",
    "coton de tulear": "Coton de Tuléar",
    "berger blanc suisse": "Berger blanc suisse",
    "berger des pyrenees": "Berger des Pyrénées",
    "montagne des pyrenees": "Montagne des Pyrénées",
    "bouledogue francais": "Bouledogue français",
    "husky de siberie": "Husky de Sibérie",
    "chat croise angora": "Chat croisé angora",
    "sacre de birmanie": "Sacré de Birmanie",
    "west highland terrier": "West Highland Terrier",
    "terrier tibetain": "Terrier tibétain",
    "epagneul tibetain": "Épagneul tibétain",
    "epagneul breton": "Épagneul breton",
    "epagneul papillon": "Épagneul papillon",
    "epagneul nain": "Épagneul nain",
    "epagneul": "Épagneul",
    "cocker spanell": "Cocker Spaniel",
    "cocker spaniel": "Cocker Spaniel",
    "bichon frise": "Bichon frisé",
    "lhassa apso": "Lhassa Apso",
    "shih tzu": "Shih Tzu",
    "shitzu": "Shih Tzu",
    "chow chow": "Chow-Chow",
    "chow-chow": "Chow-Chow",
    "golden retriever": "Golden Retriever",
    "labrador retriever": "Labrador Retriever",
    "border collie": "Border Collie",
    "bearded collie": "Bearded Collie",
    "jack russell": "Jack Russell",
    "fox terrier": "Fox Terrier",
    "bichon maltais": "Bichon maltais",
    "bichon havanais": "Bichon havanais",
    "chien de chasse": "Chien de chasse",
    "chien de berger": "Chien de berger",
    "laika de lakoutie": "Laïka de Iakoutie",
    "laika": "Laïka",
    "europeen": "Chat européen",
    "hovawart": "Hovawart",
    "caniche nain": "Caniche nain",
    "caniche royal": "Caniche royal",
    "caniche toy": "Caniche Toy",
    "spitz nain": "Spitz nain",
    "spitz loup": "Spitz loup",
    "spitz japonais": "Spitz japonais",
    "cocker anglais": "Cocker anglais",
    "cocker americain": "Cocker américain",
    "berger australien": "Berger australien",
    "berger allemand": "Berger allemand",
    "berger belge": "Berger belge",
    "levrier afghan": "Lévrier afghan",
    "levrier": "Lévrier",
    "yorkshire terrier": "Yorkshire Terrier",
    "maine coon": "Maine Coon",
    "norvegien": "Norvégien",
    "british shorthair": "British Shorthair",
    "siberien": "Sibérien",
    "shiba inu": "Shiba Inu",
    "akita inu": "Akita Inu",
    "samoyede": "Samoyède",
    "pekinois": "Pékinois",
    "scottish terrier": "Scottish Terrier",
    "terre neuve": "Terre-Neuve",
    "saint bernard": "Saint-Bernard",
    "welsh corgi": "Welsh Corgi",
    "shar pei": "Shar-Peï",
    "sharpei": "Shar-Peï",
    "dogue allemand": "Dogue allemand",
    "dogue de bordeaux": "Dogue de Bordeaux",
    "cane corso": "Cane Corso",
    "loulou de pomeranie": "Loulou de Poméranie",
    "chien loup": "Chien-loup",
    "berger picard": "Berger picard",
    "debourrage": "Débourrage",
    "demelage": "Démêlage",
    "demelage complet": "Démêlage complet",
    "epilation": "Épilation",
    "tonte integrale": "Tonte intégrale",
    "tonte integral": "Tonte intégrale",
    "bain brushing": "Bain / brushing",
    "bain/brushing": "Bain / brushing",
    "bain et brushing": "Bain / brushing",
    "coupe ciseaux": "Coupe ciseaux",
    "coupe aux ciseaux": "Coupe ciseaux",
    "coupe new look": "Coupe New Look",
    "new look": "Coupe New Look",
    "anti puces": "Anti-puces",
    "antipuce": "Anti-puces",
    "soin des yeux": "Soin des yeux",
    "glandes anales": "Glandes anales",
    "shampoing antiparasitaire": "Shampoing antiparasitaire",
    "toilettage complet": "Toilettage complet",
}

# Sigles et fautes de frappe rencontrés dans les fichiers.
ALIAS_RACES = {
    "ckc": "cavalier king charles",
    "ckg": "cavalier king charles",
    "cavalier kink charles": "cavalier king charles",
    "berded": "bearded collie",
    "berdead": "bearded collie",
    "bearded": "bearded collie",
    "coton": "coton de tulear",
    "shitzu": "shih tzu",
    "chow-chow": "chow chow",
    "golden": "golden retriever",
    "jack russel": "jack russell",
    "sharpei": "shar pei",
    "spanell": "cocker spaniel",
    "yorkshir": "yorkshire",
}

# Prestations : même principe, du plus spécifique au plus générique.
PRESTATIONS = [
    "bain brushing",
    "bain/brushing",
    "bain et brushing",
    "coupe ciseaux",
    "coupe aux ciseaux",
    "coupe new look",
    "coupe courte",
    "coupe surpeigne",
    "tonte surpeigne",
    "tonte integrale",
    "tonte integral",
    "shampoing sec",
    "shampoing antiparasitaire",
    "shampoing",
    "debourrage",
    "demelage",
    "demelage complet",
    "epilation",
    "brossage",
    "brushing",
    "toilettage complet",
    "toilettage",
    "surpeigne",
    "retouches",
    "retouche",
    "griffes",
    "oreilles",
    "glandes anales",
    "soin des yeux",
    "anti puces",
    "antipuce",
    "parfum",
    "lavage",
    "bain",
    "garde",
    "pension",
    "promenade",
    "new look",
    "tonte",
    "coupe",
]

# Modes de paiement : motif recherché -> libellé normalisé.
PAIEMENTS = [
    ("especes", "Espèces"),
    ("espece", "Espèces"),
    ("liquide", "Espèces"),
    ("cheque", "Chèque"),
    ("virement", "Virement"),
    ("carte bancaire", "CB"),
    ("carte bleue", "CB"),
    (" cb", "CB"),
    ("paypal", "PayPal"),
    ("lydia", "Lydia"),
    ("offert", "Offert"),
    ("gratuit", "Offert"),
    ("cadeau", "Offert"),
    ("echange de services", "Échange de services"),
    ("echange de service", "Échange de services"),
    ("troc", "Échange de services"),
]

# Mots qui, sur une ligne de contact, marquent la fin du nom : ce qui suit est
# un lien de parenté, un métier ou une précision, pas le patronyme.
COUPURES_NOM = [
    "patronne", "patron", "voisin", "voisine", "voisins", "fils", "fille",
    "mari", "femme", "epouse", "compagne", "compagnon", "soeur", "frere",
    "mere", "pere", "maman", "papa", "amie", "ami", "amis", "contact", "belle",
    "coiffeuse", "coiffeur", "veterinaire", "boulangere", "boulanger",
    "infirmiere", "gardien", "gardienne", "proprietaire", "alias", "dit",
    "grands", "grand", "cousine", "cousin", "tante", "oncle", "petite",
    "pour", "travaille", "rdv", "prit", "collegue", "collegues", "tata",
    "tonton", "nounou", "concierge", "menagere", "messagerie", "habite",
]

CIVILITES = [
    "mr et madame",
    "monsieur et madame",
    "madame et monsieur",
    "mme et mr",
    "mr et mme",
    "madame",
    "monsieur",
    "mademoiselle",
    "mlle",
    "melle",
    "mme",
    "mr",
    "m.",
]

# Mots qui trahissent une ligne d'adresse quand le préfixe « Adresse: » est absent.
MOTS_ADRESSE = [
    "rue",
    "avenue",
    "chemin",
    "route",
    "boulevard",
    "bd",
    "place",
    "impasse",
    "quai",
    "cour",
    "residence",
    "immeuble",
    "batiment",
    "appartement",
    "appart",
    "etage",
    "allee",
    "clos",
    "villa",
    "cottage",
    "lotissement",
    "hameau",
    "bourg",
    "lieu dit",
    "lieu-dit",
    "marinas",
    "ferme",
    "manoir",
    "square",
    "sente",
    "ruelle",
    "esplanade",
    "rond point",
    "terre rue",
    "grande rue",
    "code",
    "interphone",
    "portail",
    "portillon",
    "digicode",
    "maison",
    "pavillon",
    "parking",
    "loge",
    "sonnette",
    "sonner",
    "boite",
    "escalier",
    "camping",
    "casino",
    "golf",
    "hotel",
    "domaine",
    "haras",
    "loti",
    "chateau",
    "cite",
    "passage",
    "venelle",
    "vallee",
]

# Communes du Pays d'Auge et alentours relevées dans les fichiers : une ligne qui
# ne contient qu'un nom de commune est une adresse.
COMMUNES = [
    "trouville",
    "trouville sur mer",
    "deauville",
    "honfleur",
    "blonville",
    "blonville sur mer",
    "villers",
    "villers sur mer",
    "lisieux",
    "touques",
    "tourgeville",
    "canapville",
    "benerville",
    "villerville",
    "hennequeville",
    "equemauville",
    "saint arnoult",
    "saint gatien des bois",
    "saint gatien",
    "glos",
    "clarbec",
    "reux",
    "beuvillers",
    "caen",
    "dives sur mer",
    "dives",
    "cabourg",
    "houlgate",
    "pont l eveque",
    "pont leveque",
    "blangy le chateau",
    "blangy",
    "drucourt",
    "fourneville",
    "fatouville grestain",
    "gonneville sur honfleur",
    "manneville la pipard",
    "les authieux sur calonne",
    "la riviere saint sauveur",
    "saint hymer",
    "pierrefitte en auge",
    "mont saint leger",
    "saint vincent cramesnil",
    "vauville",
    "cricqueboeuf",
    "barneville la bertran",
    "englesqueville",
    "ablon",
    "quetteville",
    "beaumont en auge",
    "bonneville",
    "surville",
    "danestal",
    "periers en auge",
    "saint pierre azif",
    "vieux bourg",
    "genneville",
    "la haye",
    "norolles",
    "coquainvilliers",
    "ouilly du houley",
    "hermival les vaux",
    "saint desir",
    "rocques",
    "le breuil en auge",
    "bonnebosq",
    "cambremer",
    "clermont en auge",
    "victot pontfol",
]

# Lignes de synthèse mensuelle : ce ne sont pas des prestations.
MOTS_SYNTHESE = [
    "rien a declarer",
    "declare",
    "declaration du mois",
    "total du mois",
    "total mois",
    "chiffre d affaire",
    "chiffre d affaires",
    "recette du mois",
    "a declarer",
]

# Lignes de dépenses ou d'achats de matériel : ce ne sont pas des prestations.
MOTS_DEPENSE = [
    "achat", "achete", "achetee", "acheter", "depense", "depenses", "frais",
    "facture", "commande", "materiel", "remboursement", "essence", "carburant",
]

# Prénoms rencontrés dans le corpus, complétés par les prénoms français courants.
# Sert uniquement à décider si « Durand Marie » se lit « nom prénom » ou l'inverse.
PRENOMS = {
    "adele", "adrien", "agathe", "agnes", "aicha", "aime", "alain", "albert",
    "alex", "alexandra", "alexandre", "alexia", "alice", "aline", "alix",
    "alyson", "amandine", "amelie", "anais", "andre", "andrea", "angele",
    "angelique", "anne", "anne-laure", "annick", "annie", "anthony", "antoine",
    "antonin", "ariane", "arlette", "armelle", "arnaud", "arthur", "astrid",
    "aude", "audrey", "augustin", "aurelia", "aurelie", "aurelien", "aurore",
    "axel", "baptiste", "barbara", "bastien", "beatrice", "benedicte",
    "benjamin", "benoit", "bernadette", "bernard", "bertrand", "blandine",
    "brigitte", "bruno", "camille", "carine", "carole", "caroline", "casimir",
    "catherine", "cecile", "cedric", "celia", "celine", "chantal", "chantale",
    "charles", "charlene", "charlotte", "chloe", "christelle", "christian",
    "christine", "christophe", "claire", "clara", "claude", "claudine",
    "clement", "clementine", "colette", "coline", "corentin", "corinne",
    "cyril", "cyrille", "damien", "daniel", "danielle", "david", "delphine",
    "denis", "denise", "diane", "didier", "dominique", "dorothee", "edith",
    "edouard", "eliane", "elisabeth", "elise", "elodie", "eloise", "elsa",
    "emeline", "emilie", "emma", "emmanuel", "emmanuelle", "eric", "estelle",
    "esther", "etienne", "eva", "evelyne", "fabien", "fabienne", "fabrice",
    "fanny", "fatima", "flavie", "flora", "florence", "florent", "florian",
    "francine", "francis", "franck", "francois", "francoise", "frederic",
    "frederique", "gabriel", "gabrielle", "gaelle", "gaetan", "genevieve",
    "geoffrey", "georges", "gerard", "germain", "ghislaine", "gilbert",
    "gilles", "gladys", "gregory", "guillaume", "guy", "gwenael", "helene",
    "henri", "herve", "hubert", "hugo", "hugues", "ines", "irene", "isabelle",
    "jacqueline", "jacques", "james", "jean", "jean-claude", "jean-francois",
    "jean-luc", "jean-marc", "jean-michel", "jean-paul", "jean-pierre",
    "jeanne", "jennifer", "jerome", "jessica", "jo", "joel", "johanna", "john",
    "jonathan", "josette", "josiane", "joseph", "josephine", "juliette",
    "julie", "julien", "justine", "karine", "katia", "kevin", "klaudia",
    "laetitia", "laura", "laure", "laurence", "laurent", "lea", "leo",
    "leonie", "liliane", "lise", "loic", "lola", "louis", "louise", "luc",
    "lucas", "lucie", "lucien", "ludivine", "ludovic", "lydie", "madeleine",
    "magali", "manon", "marc", "marcel", "margaux", "marguerite", "maria",
    "marie", "marie-claude", "marie-jo", "marie-josee", "marie-laure",
    "marie-therese", "marina", "marine", "marion", "marlene", "martial",
    "martin", "martine", "maryline", "maryse", "mathieu", "mathilde",
    "matthieu", "maud", "maurice", "maxime", "melanie", "melissa", "michel",
    "michele", "michelle", "mickael", "mireille", "monique", "morgan",
    "muriel", "mylene", "nadege", "nadia", "nadine", "nathalie", "nicolas",
    "nicole", "nina", "noemie", "odette", "odile", "olivia", "olivier",
    "pascal", "pascale", "patrice", "patricia", "patrick", "paul", "pauline",
    "peggy", "philippe", "pierre", "pierrette", "quentin", "raphael",
    "raymond", "raymonde", "regine", "remi", "renaud", "rene", "richard",
    "rita", "robert", "romain", "romane", "rosa", "roselyne", "sabine",
    "sabrina", "samuel", "sandra", "sandrine", "sarah", "sebastien",
    "segolene", "serge", "severine", "simone", "solange", "sonia", "sophie",
    "stephane", "stephanie", "suzanne", "sylvain", "sylvie", "tanguy",
    "thibault", "thierry", "thomas", "tiphaine", "valentin", "valerie",
    "vanessa", "veronique", "victor", "victoria", "vincent", "violaine",
    "virginie", "vivien", "wafa", "william", "xavier", "yann", "yannick",
    "yves", "yvette", "yvonne", "zoe",
    # Prénoms supplémentaires relevés dans les fichiers
    "alexane", "anny", "arlene", "berenice", "chacha", "christiane",
    "elenore", "ellen", "gaia", "jessie", "katja", "loan", "maelys", "manu",
    "marcia", "pamy", "sacha", "shirley", "steve", "tiffany", "wendy",
    "angelina", "annabelle", "capucine", "coralie", "cynthia", "daphne",
    "elena", "eliott", "elyne", "fiona", "gwendoline", "ilona", "ines",
    "jocelyne", "joelle", "laurie", "lena", "leslie", "lilian", "lionel",
    "lorraine", "ludwig", "maeva", "marjorie", "maryvonne", "mathis",
    "melodie", "morgane", "nolwenn", "ophelie", "oriane", "priscilla",
    "prisca", "rachel", "rebecca", "sacha", "salome", "sarrah", "sonja",
    "stella", "sylviane", "tatiana", "theo", "valentine", "vanina",
    "yolande", "yohann", "alexis", "amaury", "aymeric", "boris", "brice",
    "cyprien", "dylan", "emile", "enzo", "evan", "fabio", "gaspard",
    "gauthier", "gregoire", "jeremy", "jules", "kylian", "leon", "lilou",
    "lucile", "marius", "mathias", "maxence", "nicolas", "noah", "octave",
    "oscar", "pierrick", "rodolphe", "ronan", "simon", "stanislas",
    "sullivan", "tristan", "ulysse", "victorien", "wilfried", "yanis",
    # Prénoms relevés lors de la relecture du rapport
    "corine", "yveline", "marylene", "muguette", "natacha", "therese",
    "alicia", "axelle", "marilyne", "marcelle", "simonne", "rose",
    "mauricette", "elie", "regis", "ruben", "arthur", "annie", "chantal",
    "michele", "michelle", "colette", "denise", "lucette", "yvette",
    "ginette", "odile", "huguette", "paulette", "jeannine", "janine",
    "solange", "renee", "monique", "eliane", "arlette", "suzanne", "sara",
}

# Particules nobiliaires : elles font partie du nom, pas du prénom.
PARTICULES = {"de", "du", "des", "d", "le", "la", "van", "von", "di", "da", "el"}

# Mots courants des annotations : une ligne composée uniquement de ces mots
# n'est pas un nom de propriétaire.
MOTS_COURANTS = {
    "tres", "trop", "peu", "assez", "bien", "mal", "gentil", "gentille",
    "gentils", "calme", "calmes", "anxieux", "anxieuse", "douillet",
    "douillette", "mignon", "mignonne", "joli", "jolie", "beau", "belle",
    "propre", "sale", "premier", "premiere", "vieux", "vieille", "jeune",
    "grand", "grande", "petit", "petite", "gros", "grosse", "boulot",
    "travail", "noeuds", "noeud", "peur", "pulseur", "muselière", "museliere",
    "mordille", "aveugle", "sourd", "arthrose", "probleme", "problemes",
    "peau", "poils", "poil", "long", "longs", "longue", "longueur", "court",
    "courts", "brosse", "douce", "rendu", "final", "correcte", "correct",
    "ensemble", "prevoir", "utiliser", "laisser", "tondre", "environ",
    "possible", "prochaine", "fois", "beaucoup", "encore", "toujours",
    "jamais", "rien", "chien", "chienne", "chat", "chatte", "chiot",
    "chaton", "animal", "ans", "an", "mois", "demi", "annee", "annees",
    "kg", "cm", "mm", "heure", "heures", "minutes", "oui", "non", "aussi",
    "sans", "avec", "mais", "donc", "car", "puis", "ainsi", "meme",
    "decevante", "decevant", "lamentable", "etat", "supplement", "pourboire",
    "pourboires", "declare", "declaration", "offert", "gratuit", "cadeau",
    "garde", "pension", "toilettage", "coupe", "tonte", "bain", "brossage",
    "shampoing", "ciseaux", "surpeigne", "debourrage", "demelage",
    "epilation", "griffes", "oreilles", "lavage", "brushing", "retouches",
    "espece", "especes", "cheque", "virement", "euros", "euro",
    "client", "clients", "cliente", "clientes", "proprio", "chiante",
}
